#!/usr/bin/env bash
# Transfers a file from our client to a server

ORIGEN=$1
IP=$2
USERNAME=$3
P_KEY=$4

if [ $#  -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ $# -eq 3 ]
	then
		scp -o "StrictHostKeyChecking no" "$ORIGEN" "$USERNAME"@"$IP":~/
	else
		scp -o "StrictHostKeyChecking no" -i "$P_KEY" "$ORIGEN" "$USERNAME"@"$IP":~/
	fi
fi
