#!/usr/bin/env bash
# Install nginx web server 

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $redirect" /etc/nginx/sites-available/default
sudo service nginx start
