#!/usr/bin/env bash
# Store Main menu

source "/etc/init.d/manage_my_process"

var=$1
case $var in
start)
	start
	echo "manage_my_process started"
	;;
restart)
	stop
	start
	echo "manage_my_process restarted"
	;;
stop)
	stop
	echo "manage_my_process stopped"
	;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
esac
exit $?
