#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" in 9 time
count=0
while [ $count -lt 11 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"	
	fi
	((count++))
done
