#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times "bad luck" for the 4
# and "Good Luck" for the 8
count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((count++))
done
