#!/usr/bin/env bash
# Script that configures the container to fit the above requirements. 
sudo pkill apache2
sudo chmod u+rw /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo service nginx restart
